# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_period',
            field=models.CharField(
                choices=[('year', 'Per Year'), ('month', 'Per Month'), ('week', 'Per Week'), ('hour', 'Per Hour')],
                default='month',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='work_days',
            field=models.CharField(
                blank=True,
                default='Monday - Friday',
                help_text="e.g. 'Monday - Friday' or 'Monday, Wednesday, Friday'",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='work_hours',
            field=models.CharField(
                blank=True,
                default='9:00 AM - 5:00 PM',
                help_text="e.g. '9:00 AM - 5:00 PM' or '40 hours/week, flexible'",
                max_length=100,
            ),
        ),
    ]
