# Generated by Django 6.0.6

import secrets

from django.db import migrations, models


def backfill_referral_codes(apps, schema_editor):
    """
    Existing users (created before this field existed) all default to an
    empty referral_code. Give each one a real unique code before we lock
    the field down with a unique constraint in the next step.
    """
    CustomUser = apps.get_model('accounts', 'CustomUser')
    existing_codes = set(CustomUser.objects.exclude(referral_code='').values_list('referral_code', flat=True))

    for user in CustomUser.objects.filter(referral_code=''):
        while True:
            code = secrets.token_hex(4).upper()
            if code not in existing_codes:
                existing_codes.add(code)
                break
        user.referral_code = code
        user.save(update_fields=['referral_code'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_referral_codes, noop_reverse),
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, unique=True),
        ),
    ]
