# Generated by Django 6.0.6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Big headline text, e.g. 'Level Up Your Setup'", max_length=100)),
                ('eyebrow', models.CharField(blank=True, help_text="Small label above the title, e.g. 'Tech Deals'", max_length=60)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('cta_text', models.CharField(default='Shop Now', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Recommended: a wide landscape photo (at least 1600x600). It will be automatically resized/optimized and cropped to fill the banner.', null=True, upload_to='hero_banners/')),
                ('placeholder_style', models.CharField(choices=[('electronics', 'Electronics (dark blue)'), ('fashion', 'Fashion (purple)'), ('home', 'Home & Kitchen (teal/green)'), ('sports', 'Sports & Outdoors (orange/pink)'), ('books', 'Books (blue/green)')], default='electronics', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, help_text="Clicking the slide's button takes shoppers to this category.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
