# Generated by Django 6.0.6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_herobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_price', models.DecimalField(decimal_places=2, help_text="Special price for the duration of the deal. Should normally be lower than the product's regular price.", max_digits=10)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to pull a deal early without deleting its record.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='products.product')),
            ],
            options={
                'verbose_name': 'Deal of the Day',
                'verbose_name_plural': 'Deals of the Day',
                'ordering': ['starts_at'],
            },
        ),
    ]
